Fix database template and add db classify template #13
vinhyenvodoi98/LLM_hackathon_2023 pull request #15
Opened 2023-10-01 13:30 UTC by tienthegainz

# Descriptions
- Update db template
- Add db attributes sample for database

# TODO
- #4

2023-10-01 14:34 UTC, dduong166 requested changes
có comment nha

2023-10-01 14:34 UTC, dduong166 commented on backend/sample_data/database_template.json5
>                  "SMALL",
để là Small, Medium,.. hoặc small, medium,... thôi nhé.
Tất cả in hoa ở đây thì model phân tích token bị phức tạp hơn 1 cách k cần thiết.
https://learn.activeloop.ai/courses/take/langchain/multimedia/46866912-understanding-tokens

2023-10-01 14:34 UTC, dduong166 commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
1 số description có vẻ cần mô tả chi tiết hơn.
Vừa là để model hiểu hơn về từng field, vừa là để hiển thị lên[ explain modal](https://docs.google.com/spreadsheets/d/1ol75s1eD2eiiF0fPJbvzV75oWcjxW8jkqq7VL7ynNSI/edit#gid=1063153457&range=O35:O40)

2023-10-02 12:48 UTC, tienthegainz commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
Những trường nào hiện tại đang có độ chính xác không cao vậy?

2023-10-02 12:56 UTC, dduong166 reviewed
thêm comment nha

2023-10-02 12:56 UTC, dduong166 commented on backend/sample_data/database_template.json5
>              "description": "Is read consistency (any read request will return the most recent write) one of the most important requirements?"
"one of the most important requirements?" -> từ này dễ gây lack of information vì nếu user k nói thẳng ra thì cũng khó suy luận dựa trên dữ liệu có sẵn

2023-10-02 12:59 UTC, dduong166 commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
tôi chưa chạy với template mới này, thấy cũng thay đổi kha khá so với template cũ nên k nói trước đc cái nào có độ chính xác k cao

2023-10-02 13:01 UTC, tienthegainz commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
@dduong166 
Thế ông chạy đi xong xem những field nào đang có độ chính xác không cao đi, xong để t sửa 1 lần luôn

2023-10-02 13:31 UTC, dduong166 commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
oke cũng tốn tgian vì phải sửa lại cả đống example

2023-10-02 14:27 UTC, dduong166 commented on backend/sample_data/database_template.json5
> +            "description": "Is your data structured?"
chắc ông cứ viết text để hiện lên modal là đc nhé.
Text giải thích trong prompt thì tôi tự viết riêng cho tối ưu.
Nên ông cũng k cần quan tâm trường nào đang có độ chính xác k cao nữa

2023-10-03 13:20 UTC, vannhi1118 approved these changes

2023-10-03 13:20 UTC, vannhi1118 commented on backend/sample_data/database_template.json5
> +                // NOTE: for SQL và NoSQL database, basic type of data will be:
for SQL and NoSQL =))

2023-10-04 12:52 UTC, merged