#14 create llm base and interactor
vinhyenvodoi98/LLM_hackathon_2023 pull request #16
Opened 2023-10-02 12:51 UTC by vannhi1118

# Description
- Create LLM base: 
  - Different types of model initialization
  - Different types of prompt class 

- Create prompt config files to test LLM

# TODO
- Study if we can use Output Parser to get a better formatted output
- Add output formatting logics
- Add comments where needed

2023-10-03 12:55 UTC, dduong166 approved these changes
LGTM

2023-10-04 00:05 UTC, tienthegainz commented on backend/llm/llm_base/palm_model.py
> +
Thêm new line vào cuối file này nhé

2023-10-04 00:05 UTC, tienthegainz commented on backend/llm/llm_base/output_parser.py
> +
Thêm new line vào cuối file này nhé

2023-10-04 00:06 UTC, tienthegainz requested changes
Với cả phần requirements của LLM, @vannhi1118 merge vào với phần requirement chung của app.

Làm xong thì merge nhé

2023-10-08 06:06 UTC, merged