Issue 5
vinhyenvodoi98/LLM_hackathon_2023 pull request #7
Opened 2023-09-30 09:16 UTC by vannhi1118

## Description
- Setup environment to test LLM locally
- Might not be optimal for CI/CD? Need confirmations from reviewers.

## TODO
- Design utils modules or classes for backend to use LLM
- Prompt design to get the required output

2023-09-30 09:32 UTC, vinhyenvodoi98 approved these changes
LGTM

2023-09-30 10:48 UTC, tienthegainz commented on backend/llm/test.py
> +llm = load_llm("./llm_setup_data/llm.json")
Cái này là gì đây?

2023-09-30 10:50 UTC, tienthegainz requested changes
Viết thêm một cái base class để lấy API_KEY các thứ rồi build llm trong cùng một file luôn đi.

Ngoài ra bạn có một vài comment sau đây

2023-09-30 10:56 UTC, vannhi1118 commented on backend/llm/test.py
> +llm = load_llm("./llm_setup_data/llm.json")
À quên, lúc đấy đang test dở mà langchain chưa hỗ trợ cho Palm nên ko dùng đc. Để bạn sửa lại chỗ này

2023-09-30 11:04 UTC, vannhi1118 commented
> Viết thêm một cái base class để lấy API_KEY các thứ rồi build llm trong cùng một file luôn đi.

Cái này bạn định điều tra xong dùng prompt các thứ thế nào thì mới design. Mai rồi update 😃 

> Ngoài ra bạn có một vài comment sau đây

Comment đâu =)))

2023-09-30 11:25 UTC, tienthegainz commented on backend/llm/test.py
> +llm = load_llm("./llm_setup_data/llm.json")
@vannhi1118 

> Comment đâu =)))

Đây nhé

2023-09-30 12:30 UTC, dduong166 commented
LGTM

2023-09-30 12:32 UTC, dduong166 approved these changes
LGTM

2023-10-01 01:36 UTC, vannhi1118 commented
@tienthegainz 
Bạn move file test sang folder /backend/scripts rồi nhé

2023-10-01 03:43 UTC, tienthegainz commented
> Bạn move file test sang folder /backend/scripts rồi nhé

File đâu rồi vậy?

2023-10-01 04:19 UTC, tienthegainz approved these changes

2023-10-01 04:49 UTC, merged